/** Auto-generated by scripts/build-floors.py — do not edit by hand. */

export const POT5F_PAGE = {
  width: 1549.4399,
  height: 1097.4399,
} as const;

export const POT5F_VIEWBOX = {
  x: 99,
  y: 342,
  width: 978,
  height: 496,
} as const;

export const POT5F_ROOMS = [
  {
    roomId: "pot5-meeting",
    name: "Meeting",
    capacity: 5,
    x: 172.62,
    y: 397.19,
    width: 81.19,
    height: 73.62,
    labelX: 213.22,
    labelY: 434.00,
    path: "M172.62,397.19 L172.62,470.81 L184.31,470.75 L183.44,469.75 L183.88,468.19 L181.25,468.19 L178.69,465.50 L178.69,430.12 L181.25,427.44 L188.88,427.44 L191.44,430.12 L191.00,466.06 L202.38,466.06 L203.25,465.19 L206.50,465.19 L208.56,467.25 L208.56,468.75 L206.56,470.75 L211.62,470.81 L210.81,468.75 L213.38,466.06 L230.00,466.06 L233.25,462.81 L240.38,462.81 L242.94,465.50 L242.94,467.25 L240.38,469.94 L234.62,470.06 L234.25,470.81 L253.81,470.75 L253.81,448.50 L251.62,448.44 L248.94,445.75 L248.88,397.19 L172.62,397.19 Z",
  },
] as const;
