import type { DashboardData } from "@/lib/types";

export const STORAGE_KEY = "hsh-dashboard-v1";

export const seedData: DashboardData = {
  incidents: [
    {
      id: "INC-1042",
      title: "Unsecured pallet jack rolled toward pedestrian aisle",
      site: "North Wharf",
      category: "near-miss",
      severity: "high",
      status: "investigating",
      reportedBy: "Owen Blake",
      reportedAt: "2026-08-31T14:20:00.000Z",
      description:
        "A pallet jack left on a 3° slope rolled six metres toward the marked pedestrian route. No contact. Brake lock was not engaged.",
    },
    {
      id: "INC-1041",
      title: "Hand laceration while changing a conveyor scraper",
      site: "Process Hall",
      category: "injury",
      severity: "medium",
      status: "open",
      reportedBy: "Sam Okonkwo",
      reportedAt: "2026-08-29T09:05:00.000Z",
      description:
        "Fitters changed a worn scraper without cut-resistant gloves. Superficial laceration to the left palm. First aid given on site.",
    },
    {
      id: "INC-1040",
      title: "Listeria swab failed on packing table 4",
      site: "Cold Store",
      category: "hygiene",
      severity: "high",
      status: "investigating",
      reportedBy: "Priya Nair",
      reportedAt: "2026-08-28T16:40:00.000Z",
      description:
        "Routine swab returned a presumptive positive. Line isolated. Deep clean scheduled before the next production window.",
    },
    {
      id: "INC-1039",
      title: "Diesel drip under parked yard tractor",
      site: "Fleet Yard",
      category: "environment",
      severity: "low",
      status: "closed",
      reportedBy: "Elena Voss",
      reportedAt: "2026-08-22T11:10:00.000Z",
      description:
        "Small drip under tractor 12. Spill kit used. Workshop replaced a cracked return hose the same shift.",
    },
    {
      id: "INC-1038",
      title: "Forklift clipped racking upright in bay C",
      site: "North Wharf",
      category: "property",
      severity: "medium",
      status: "closed",
      reportedBy: "Owen Blake",
      reportedAt: "2026-08-18T07:55:00.000Z",
      description:
        "Low-speed contact with racking. Upright inspected and tagged. Temporary load restriction in place until replacement arrives.",
    },
    {
      id: "INC-1034",
      title: "Lost-time ankle sprain on wet stairs",
      site: "Admin Annex",
      category: "injury",
      severity: "high",
      status: "closed",
      reportedBy: "Maya Chen",
      reportedAt: "2026-07-16T08:30:00.000Z",
      description:
        "Contractor slipped on rainwater tracked onto the annex stair. Three days lost time. Matting and canopy work completed.",
    },
    {
      id: "INC-1032",
      title: "Near miss: unlabelled chemical tote in wash bay",
      site: "Process Hall",
      category: "near-miss",
      severity: "medium",
      status: "closed",
      reportedBy: "Priya Nair",
      reportedAt: "2026-08-04T13:15:00.000Z",
      description:
        "A 20 L tote of caustic solution sat without a GHS label for one shift. Removed and relabelled. Toolbox talk completed.",
    },
    {
      id: "INC-1028",
      title: "Hot water scald during CIP rinse",
      site: "Process Hall",
      category: "injury",
      severity: "critical",
      status: "closed",
      reportedBy: "Maya Chen",
      reportedAt: "2026-07-16T06:10:00.000Z",
      description:
        "Operator received a second-degree scald when a CIP valve was opened against procedure. Isolation lock added to the valve.",
    },
  ],
  inspections: [
    {
      id: "INS-221",
      title: "Weekly hygiene walk of packing hall",
      site: "Cold Store",
      type: "hygiene",
      scheduledFor: "2026-09-01",
      inspector: "Priya Nair",
      status: "upcoming",
    },
    {
      id: "INS-220",
      title: "PPE spot check — night shift",
      site: "Process Hall",
      type: "ppe",
      scheduledFor: "2026-09-02",
      inspector: "Owen Blake",
      status: "upcoming",
    },
    {
      id: "INS-219",
      title: "Fire door and extinguisher round",
      site: "Admin Annex",
      type: "fire",
      scheduledFor: "2026-08-29",
      inspector: "Elena Voss",
      status: "overdue",
    },
    {
      id: "INS-218",
      title: "Forklift pre-use and charging bay",
      site: "North Wharf",
      type: "equipment",
      scheduledFor: "2026-08-30",
      inspector: "Sam Okonkwo",
      status: "overdue",
    },
    {
      id: "INS-217",
      title: "Housekeeping — loading docks",
      site: "North Wharf",
      type: "housekeeping",
      scheduledFor: "2026-08-27",
      inspector: "Owen Blake",
      status: "complete",
      score: 86,
    },
    {
      id: "INS-216",
      title: "Hygiene — handwash and boot wash",
      site: "Process Hall",
      type: "hygiene",
      scheduledFor: "2026-08-25",
      inspector: "Priya Nair",
      status: "complete",
      score: 92,
    },
    {
      id: "INS-215",
      title: "Hygiene — Cold Store high-care",
      site: "Cold Store",
      type: "hygiene",
      scheduledFor: "2026-08-18",
      inspector: "Priya Nair",
      status: "complete",
      score: 74,
    },
    {
      id: "INS-214",
      title: "Yard diesel bund and spill kits",
      site: "Fleet Yard",
      type: "equipment",
      scheduledFor: "2026-08-20",
      inspector: "Sam Okonkwo",
      status: "complete",
      score: 81,
    },
  ],
  actions: [
    {
      id: "ACT-318",
      title: "Replace cut-resistant glove stock at Process Hall stores",
      relatedTo: "INC-1041",
      owner: "Sam Okonkwo",
      due: "2026-09-03",
      status: "open",
      priority: "high",
    },
    {
      id: "ACT-317",
      title: "Add slope markers and park-brake reminder at North Wharf",
      relatedTo: "INC-1042",
      owner: "Owen Blake",
      due: "2026-09-05",
      status: "open",
      priority: "high",
    },
    {
      id: "ACT-316",
      title: "Complete deep clean and re-swab packing table 4",
      relatedTo: "INC-1040",
      owner: "Priya Nair",
      due: "2026-08-31",
      status: "overdue",
      priority: "critical",
    },
    {
      id: "ACT-315",
      title: "Order replacement racking upright for bay C",
      relatedTo: "INC-1038",
      owner: "Elena Voss",
      due: "2026-09-12",
      status: "open",
      priority: "medium",
    },
    {
      id: "ACT-310",
      title: "Install canopy over annex stair landing",
      relatedTo: "INC-1034",
      owner: "Maya Chen",
      due: "2026-08-10",
      status: "done",
      priority: "high",
    },
    {
      id: "ACT-308",
      title: "Fit isolation lock to CIP rinse valve 3",
      relatedTo: "INC-1028",
      owner: "Sam Okonkwo",
      due: "2026-07-20",
      status: "done",
      priority: "critical",
    },
  ],
};
