import type { Booking, HubStory, Room, SharePointItem } from "@/lib/types";
import { todayInZone, zonedDateTime } from "@/lib/time";

function at(date: string, time: string) {
  const [hour, minute] = time.split(":").map(Number);
  return zonedDateTime(date, hour, minute).toISOString();
}

export function seedRooms(): Room[] {
  return [
    {
      id: "boardroom-a",
      name: "Boardroom A",
      email: "boardroom.a@hsh.example",
      capacity: 12,
      floor: "POT12F",
      equipment: ["Teams Room", "Whiteboard"],
    },
    {
      id: "pot12-interview",
      name: "Interview 12",
      email: "interview.12@hsh.example",
      capacity: 4,
      floor: "POT12F",
      equipment: ["Phone"],
    },
    {
      id: "quiet-room",
      name: "Quiet Room",
      email: "quiet.room@hsh.example",
      capacity: 4,
      floor: "POT12F",
      equipment: ["Phone"],
    },
    {
      id: "collaboration-2",
      name: "Collaboration 2",
      email: "collab.2@hsh.example",
      capacity: 6,
      floor: "POT12F",
      equipment: ["TV", "HDMI"],
    },
    {
      id: "pot12-huddle",
      name: "Huddle 12",
      email: "huddle.12@hsh.example",
      capacity: 6,
      floor: "POT12F",
      equipment: ["TV"],
    },
    {
      id: "pot12-training",
      name: "Training 12",
      email: "training.12@hsh.example",
      capacity: 16,
      floor: "POT12F",
      equipment: ["Projector", "Teams Room"],
    },
    {
      id: "pot14-boardroom",
      name: "Boardroom 14",
      email: "boardroom.14@hsh.example",
      capacity: 10,
      floor: "POT14F",
      equipment: ["Teams Room", "Whiteboard"],
    },
    {
      id: "pot14-interview",
      name: "Interview 14",
      email: "interview.14@hsh.example",
      capacity: 4,
      floor: "POT14F",
      equipment: ["Phone"],
    },
    {
      id: "pot14-focus",
      name: "Focus 14",
      email: "focus.14@hsh.example",
      capacity: 4,
      floor: "POT14F",
      equipment: ["Phone"],
    },
    {
      id: "pot14-collab",
      name: "Collaboration 14",
      email: "collab.14@hsh.example",
      capacity: 8,
      floor: "POT14F",
      equipment: ["TV", "HDMI"],
    },
    {
      id: "pot14-huddle",
      name: "Huddle 14",
      email: "huddle.14@hsh.example",
      capacity: 6,
      floor: "POT14F",
      equipment: ["TV"],
    },
    {
      id: "pot14-training",
      name: "Training 14",
      email: "training.14@hsh.example",
      capacity: 14,
      floor: "POT14F",
      equipment: ["Projector", "Teams Room"],
    },
    {
      id: "sgb-boardroom",
      name: "SGB Boardroom",
      email: "sgb.boardroom@hsh.example",
      capacity: 14,
      floor: "SGB",
      equipment: ["Teams Room", "Whiteboard"],
    },
    {
      id: "sgb-huddle",
      name: "SGB Huddle",
      email: "sgb.huddle@hsh.example",
      capacity: 6,
      floor: "SGB",
      equipment: ["TV"],
    },
    {
      id: "sgb-focus",
      name: "SGB Focus",
      email: "sgb.focus@hsh.example",
      capacity: 4,
      floor: "SGB",
      equipment: ["Phone"],
    },
    {
      id: "sgb-collab",
      name: "SGB Collab",
      email: "sgb.collab@hsh.example",
      capacity: 8,
      floor: "SGB",
      equipment: ["TV", "HDMI"],
    },
    {
      id: "sgb-training",
      name: "SGB Training",
      email: "sgb.training@hsh.example",
      capacity: 12,
      floor: "SGB",
      equipment: ["Projector"],
    },
    {
      id: "hub-studio",
      name: "HSH Hub Studio",
      email: "hub.studio@hsh.example",
      capacity: 20,
      floor: "SGB",
      equipment: ["Projector", "Mic", "Teams Room"],
    },
  ];
}

/** Mock presence: rooms with someone inside, whether booked or free. */
export function seedInUseRoomIds(): string[] {
  return [
    "boardroom-a",
    "hub-studio",
    "pot12-huddle",
    "pot14-interview",
    "pot14-huddle",
    "sgb-focus",
  ];
}

export function seedBookings(date = todayInZone()): Booking[] {
  return [
    {
      id: "evt-1001",
      roomId: "boardroom-a",
      title: "Weekly ops stand-up",
      organizer: "Maya Chen",
      start: at(date, "08:30"),
      end: at(date, "09:15"),
      source: "outlook",
    },
    {
      id: "evt-1006",
      roomId: "boardroom-a",
      title: "Capital works briefing",
      organizer: "James Liu",
      start: at(date, "09:30"),
      end: at(date, "10:30"),
      source: "outlook",
    },
    {
      id: "evt-1002",
      roomId: "boardroom-a",
      title: "Vendor review — facilities",
      organizer: "Elena Voss",
      start: at(date, "11:00"),
      end: at(date, "12:30"),
      source: "outlook",
    },
    {
      id: "evt-1007",
      roomId: "boardroom-a",
      title: "Peninsula brand workshop",
      organizer: "Clara Ng",
      start: at(date, "13:00"),
      end: at(date, "14:00"),
      source: "outlook",
    },
    {
      id: "evt-1008",
      roomId: "boardroom-a",
      title: "Board papers review",
      organizer: "Elena Voss",
      start: at(date, "15:00"),
      end: at(date, "16:30"),
      source: "outlook",
    },
    {
      id: "evt-1009",
      roomId: "boardroom-a",
      title: "Close-of-day wrap",
      organizer: "Maya Chen",
      start: at(date, "17:00"),
      end: at(date, "17:45"),
      source: "outlook",
    },
    {
      id: "evt-1010",
      roomId: "collaboration-2",
      title: "IT stand-up",
      organizer: "Noah Patel",
      start: at(date, "07:30"),
      end: at(date, "08:15"),
      source: "outlook",
    },
    {
      id: "evt-1003",
      roomId: "collaboration-2",
      title: "HSH Hub content planning",
      organizer: "Priya Nair",
      start: at(date, "09:00"),
      end: at(date, "10:00"),
      source: "outlook",
    },
    {
      id: "evt-1011",
      roomId: "collaboration-2",
      title: "Guest experience huddle",
      organizer: "Amira Hassan",
      start: at(date, "10:15"),
      end: at(date, "11:00"),
      source: "outlook",
    },
    {
      id: "evt-1012",
      roomId: "collaboration-2",
      title: "Lunch & learn — fire safety",
      organizer: "Workplace",
      start: at(date, "12:00"),
      end: at(date, "13:00"),
      source: "outlook",
    },
    {
      id: "evt-1013",
      roomId: "collaboration-2",
      title: "Website IA review",
      organizer: "Priya Nair",
      start: at(date, "14:00"),
      end: at(date, "15:30"),
      source: "outlook",
    },
    {
      id: "evt-1014",
      roomId: "collaboration-2",
      title: "Vendor onboarding",
      organizer: "James Liu",
      start: at(date, "16:00"),
      end: at(date, "17:00"),
      source: "outlook",
    },
    {
      id: "evt-1015",
      roomId: "hub-studio",
      title: "Media training",
      organizer: "Clara Ng",
      start: at(date, "08:00"),
      end: at(date, "09:00"),
      source: "outlook",
    },
    {
      id: "evt-1016",
      roomId: "hub-studio",
      title: "Leadership forum",
      organizer: "Owen Blake",
      start: at(date, "10:00"),
      end: at(date, "11:30"),
      source: "outlook",
    },
    {
      id: "evt-1017",
      roomId: "hub-studio",
      title: "Staff briefing",
      organizer: "HSH Hub",
      start: at(date, "12:30"),
      end: at(date, "13:30"),
      source: "outlook",
    },
    {
      id: "evt-1004",
      roomId: "hub-studio",
      title: "All-hands rehearsal",
      organizer: "Owen Blake",
      start: at(date, "14:00"),
      end: at(date, "16:00"),
      source: "outlook",
    },
    {
      id: "evt-1018",
      roomId: "hub-studio",
      title: "Community event setup",
      organizer: "Amira Hassan",
      start: at(date, "16:30"),
      end: at(date, "18:00"),
      source: "outlook",
    },
    {
      id: "evt-1019",
      roomId: "quiet-room",
      title: "Confidential call",
      organizer: "Noah Patel",
      start: at(date, "08:00"),
      end: at(date, "08:30"),
      source: "outlook",
    },
    {
      id: "evt-1020",
      roomId: "quiet-room",
      title: "Recruitment screen",
      organizer: "HR",
      start: at(date, "09:00"),
      end: at(date, "09:45"),
      source: "outlook",
    },
    {
      id: "evt-1005",
      roomId: "quiet-room",
      title: "1:1 coaching",
      organizer: "Sam Okonkwo",
      start: at(date, "10:30"),
      end: at(date, "11:00"),
      source: "outlook",
    },
    {
      id: "evt-1021",
      roomId: "quiet-room",
      title: "Payroll query",
      organizer: "Finance",
      start: at(date, "11:15"),
      end: at(date, "12:00"),
      source: "outlook",
    },
    {
      id: "evt-1022",
      roomId: "quiet-room",
      title: "EAP session",
      organizer: "Sam Okonkwo",
      start: at(date, "13:30"),
      end: at(date, "14:00"),
      source: "outlook",
    },
    {
      id: "evt-1023",
      roomId: "quiet-room",
      title: "Legal consult",
      organizer: "James Liu",
      start: at(date, "15:00"),
      end: at(date, "15:30"),
      source: "outlook",
    },
    {
      id: "evt-1024",
      roomId: "quiet-room",
      title: "Performance check-in",
      organizer: "Maya Chen",
      start: at(date, "16:15"),
      end: at(date, "17:00"),
      source: "outlook",
    },
    {
      id: "evt-1025",
      roomId: "pot14-boardroom",
      title: "Brand committee",
      organizer: "Clara Ng",
      start: at(date, "09:00"),
      end: at(date, "10:30"),
      source: "outlook",
    },
    {
      id: "evt-1026",
      roomId: "pot14-boardroom",
      title: "Budget working session",
      organizer: "Elena Voss",
      start: at(date, "13:00"),
      end: at(date, "15:00"),
      source: "outlook",
    },
    {
      id: "evt-1027",
      roomId: "pot14-boardroom",
      title: "Vendor close-out",
      organizer: "James Liu",
      start: at(date, "16:00"),
      end: at(date, "17:00"),
      source: "outlook",
    },
    {
      id: "evt-1028",
      roomId: "pot14-collab",
      title: "Design critique",
      organizer: "Priya Nair",
      start: at(date, "08:30"),
      end: at(date, "09:30"),
      source: "outlook",
    },
    {
      id: "evt-1029",
      roomId: "pot14-collab",
      title: "Intranet workshop",
      organizer: "Noah Patel",
      start: at(date, "11:00"),
      end: at(date, "12:30"),
      source: "outlook",
    },
    {
      id: "evt-1030",
      roomId: "pot14-collab",
      title: "Stand-up overflow",
      organizer: "Maya Chen",
      start: at(date, "15:30"),
      end: at(date, "16:15"),
      source: "outlook",
    },
    {
      id: "evt-1031",
      roomId: "pot14-focus",
      title: "Candidate screen",
      organizer: "HR",
      start: at(date, "10:00"),
      end: at(date, "10:45"),
      source: "outlook",
    },
    {
      id: "evt-1032",
      roomId: "pot14-focus",
      title: "Counsel call",
      organizer: "Legal",
      start: at(date, "14:00"),
      end: at(date, "14:30"),
      source: "outlook",
    },
    {
      id: "evt-1033",
      roomId: "sgb-boardroom",
      title: "GM briefing",
      organizer: "Owen Blake",
      start: at(date, "08:00"),
      end: at(date, "09:00"),
      source: "outlook",
    },
    {
      id: "evt-1034",
      roomId: "sgb-boardroom",
      title: "Hotel operations review",
      organizer: "Amira Hassan",
      start: at(date, "11:00"),
      end: at(date, "12:30"),
      source: "outlook",
    },
    {
      id: "evt-1035",
      roomId: "sgb-boardroom",
      title: "Evening wrap",
      organizer: "Owen Blake",
      start: at(date, "16:30"),
      end: at(date, "17:30"),
      source: "outlook",
    },
    {
      id: "evt-1036",
      roomId: "sgb-huddle",
      title: "Duty manager handoff",
      organizer: "Front office",
      start: at(date, "07:30"),
      end: at(date, "08:00"),
      source: "outlook",
    },
    {
      id: "evt-1037",
      roomId: "sgb-huddle",
      title: "Guest recovery",
      organizer: "Amira Hassan",
      start: at(date, "13:00"),
      end: at(date, "13:45"),
      source: "outlook",
    },
    {
      id: "evt-1038",
      roomId: "sgb-huddle",
      title: "Night audit prep",
      organizer: "Finance",
      start: at(date, "17:00"),
      end: at(date, "17:45"),
      source: "outlook",
    },
    {
      id: "evt-1039",
      roomId: "pot12-interview",
      title: "Campus interview",
      organizer: "HR",
      start: at(date, "09:30"),
      end: at(date, "10:15"),
      source: "outlook",
    },
    {
      id: "evt-1040",
      roomId: "pot12-interview",
      title: "Reference call",
      organizer: "Maya Chen",
      start: at(date, "14:00"),
      end: at(date, "14:30"),
      source: "outlook",
    },
    {
      id: "evt-1041",
      roomId: "pot12-huddle",
      title: "Sprint huddle",
      organizer: "Noah Patel",
      start: at(date, "10:00"),
      end: at(date, "10:30"),
      source: "outlook",
    },
    {
      id: "evt-1042",
      roomId: "pot12-huddle",
      title: "Release dry-run",
      organizer: "Priya Nair",
      start: at(date, "15:00"),
      end: at(date, "16:00"),
      source: "outlook",
    },
    {
      id: "evt-1043",
      roomId: "pot12-training",
      title: "Fire warden briefing",
      organizer: "Workplace",
      start: at(date, "08:30"),
      end: at(date, "09:30"),
      source: "outlook",
    },
    {
      id: "evt-1044",
      roomId: "pot12-training",
      title: "Outlook room training",
      organizer: "IT",
      start: at(date, "13:00"),
      end: at(date, "15:00"),
      source: "outlook",
    },
    {
      id: "evt-1045",
      roomId: "pot14-interview",
      title: "Agency briefing",
      organizer: "Clara Ng",
      start: at(date, "11:00"),
      end: at(date, "11:45"),
      source: "outlook",
    },
    {
      id: "evt-1046",
      roomId: "pot14-interview",
      title: "Offer discussion",
      organizer: "HR",
      start: at(date, "16:00"),
      end: at(date, "16:30"),
      source: "outlook",
    },
    {
      id: "evt-1047",
      roomId: "pot14-huddle",
      title: "Content desk huddle",
      organizer: "Priya Nair",
      start: at(date, "09:00"),
      end: at(date, "09:30"),
      source: "outlook",
    },
    {
      id: "evt-1048",
      roomId: "pot14-huddle",
      title: "Campaign check",
      organizer: "Clara Ng",
      start: at(date, "14:30"),
      end: at(date, "15:15"),
      source: "outlook",
    },
    {
      id: "evt-1049",
      roomId: "pot14-training",
      title: "Manager induction",
      organizer: "Workplace",
      start: at(date, "10:00"),
      end: at(date, "12:00"),
      source: "outlook",
    },
    {
      id: "evt-1050",
      roomId: "pot14-training",
      title: "Systems walkthrough",
      organizer: "Noah Patel",
      start: at(date, "15:30"),
      end: at(date, "17:00"),
      source: "outlook",
    },
    {
      id: "evt-1051",
      roomId: "sgb-focus",
      title: "Private call",
      organizer: "Owen Blake",
      start: at(date, "09:00"),
      end: at(date, "09:30"),
      source: "outlook",
    },
    {
      id: "evt-1052",
      roomId: "sgb-focus",
      title: "Counsel note",
      organizer: "Legal",
      start: at(date, "15:00"),
      end: at(date, "15:30"),
      source: "outlook",
    },
    {
      id: "evt-1053",
      roomId: "sgb-collab",
      title: "Duty roster",
      organizer: "Front office",
      start: at(date, "10:30"),
      end: at(date, "11:15"),
      source: "outlook",
    },
    {
      id: "evt-1054",
      roomId: "sgb-collab",
      title: "Event run-of-show",
      organizer: "Amira Hassan",
      start: at(date, "14:00"),
      end: at(date, "15:30"),
      source: "outlook",
    },
    {
      id: "evt-1055",
      roomId: "sgb-training",
      title: "Service standard drill",
      organizer: "HSH Hub",
      start: at(date, "08:30"),
      end: at(date, "10:00"),
      source: "outlook",
    },
    {
      id: "evt-1056",
      roomId: "sgb-training",
      title: "Night team briefing",
      organizer: "Owen Blake",
      start: at(date, "16:00"),
      end: at(date, "17:00"),
      source: "outlook",
    },
  ];
}

export function seedHub(): HubStory[] {
  return [
    {
      id: "hub-1",
      title: "Site induction refresh starts Monday",
      summary:
        "All contractors on North Wharf need the updated HSH Hub induction before signing in next week.",
      publishedAt: new Date().toISOString(),
      author: "HSH Hub",
      href: "https://hub.hsh.example/induction",
    },
    {
      id: "hub-2",
      title: "Cafeteria hours change this Thursday",
      summary:
        "Ground-floor servery closes at 14:30 for a kitchen deep clean. Hub Studio bookings are unaffected.",
      publishedAt: new Date(Date.now() - 3_600_000).toISOString(),
      author: "Workplace",
      href: "https://hub.hsh.example/cafeteria",
    },
    {
      id: "hub-3",
      title: "New Teams Room in Boardroom A",
      summary:
        "Tap to join is live. Book the room as usual from this board or from Outlook.",
      publishedAt: new Date(Date.now() - 86_400_000).toISOString(),
      author: "IT",
      href: "https://hub.hsh.example/teams-rooms",
    },
  ];
}

export function seedSharePoint(): SharePointItem[] {
  return [
    {
      id: "sp-1",
      name: "HSH visitor protocol.docx",
      library: "Workplace / Policies",
      modifiedAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
      modifiedBy: "Elena Voss",
      href: "https://hsh.sharepoint.example/policies/visitor",
      kind: "document",
    },
    {
      id: "sp-2",
      name: "Room kit checklist",
      library: "Facilities / Lists",
      modifiedAt: new Date(Date.now() - 4 * 86_400_000).toISOString(),
      modifiedBy: "Owen Blake",
      href: "https://hsh.sharepoint.example/lists/room-kit",
      kind: "list",
    },
    {
      id: "sp-3",
      name: "September site notice",
      library: "Communication site",
      modifiedAt: new Date(Date.now() - 6 * 3_600_000).toISOString(),
      modifiedBy: "Priya Nair",
      href: "https://hsh.sharepoint.example/sitepages/september",
      kind: "page",
    },
    {
      id: "sp-4",
      name: "Floor 2 evacuation map.pdf",
      library: "H&S / Documents",
      modifiedAt: new Date(Date.now() - 12 * 86_400_000).toISOString(),
      modifiedBy: "Maya Chen",
      href: "https://hsh.sharepoint.example/hs/evac-l2",
      kind: "document",
    },
  ];
}
